---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Blog
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
- type: heading
  label: Pages
- type: document
  path: content/about/_index.md
  label: About
- type: document
  path: content/contact/_index.md
  label: Contact
- type: heading
  label: Other Things
- type: directory
  path: content/jobs
  label: Jobs
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: content/lists/employees
  label: Employees
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - employees
- type: directory
  path: content/lists/member_startups
  label: Member Startups
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - member-startup
upload_dir: static/media
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -D
  publish_command: hugo
  output_directory: public
version: '0.53'
