---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
- type: heading
  label: Pages
- type: document
  path: content/contact/_index.md
  label: Contact
  read_only: false
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
- type: heading
  label: Items
- type: directory
  path: content/itemized
  label: Itemized
  create: all
  match: "**/*"
upload_dir: static/media
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -D
  publish_command: hugo
  output_directory: public
version: '0.53'
